# 📂 Исключаем внешние папки
excluded:
  - Carthage
  - Pods
  - fastlane
  - .build
  - .github
  - Generated

# 🚫 Отключаем некоторые спорные правила
disabled_rules:
  - line_length
  - file_length
  - type_name
  - identifier_name
  - force_cast
  - trailing_whitespace

# ✅ Включаем строгие, но важные правила
opt_in_rules:
  - empty_count
  - explicit_init
  - sorted_imports
  - attributes
  - missing_docs
  - fatal_error_message
  - toggle_bool
  - unused_declaration
  - unused_import
  - multiline_parameters_brackets

# 📏 Настройки
line_length:
  warning: 120
  error: 180

identifier_name:
  excluded:
    - id
    - URL
    - x
    - y
    - z

# 🔐 Кастомные запрещённые паттерны
custom_rules:
  no_print:
    name: "Print statements not allowed"
    regex: "print\\s*\\("
    message: "Не используй print — используй Logger или os_log"
    severity: warning

  no_debug_log:
    name: "Debug лог не должен попадать в production"
    regex: "(debugLog|debug_log|log.debug)"
    message: "Удали debug логи перед пушем"
    severity: warning

  no_todo:
    name: "TODO нужно решать"
    regex: "(//\\s*TODO|#\\s*TODO)"
    message: "Найден TODO — оформи задачу или реши"
    severity: warning

  no_force_unwrap:
    name: "Avoid force unwrap"
    regex: "!\\s*[^=]"
    match_kinds: expression
    message: "Нельзя использовать force unwrap — используй optional binding"
    severity: error

