name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint

      - name: Run tests
        run: |
          xcodebuild test \
            -project PaymentDemoApp.xcodeproj \
            -scheme PaymentDemoApp \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' \
            -skipPackagePluginValidation \
            -resultBundlePath TestResults

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults

