name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Install dependencies (if any)
        run: echo "No dependencies to install"

      - name: Run tests
        run: |
          xcodebuild test \
            -project PaymentDemoApp.xcodeproj \
            -scheme PaymentDemoApp \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' \
            -skipPackagePluginValidation \
            -resultBundlePath TestResults

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults

